### PR TITLE
Add ability to attach the hook to additional extensions

### PR DESCRIPTION
**Pull request by sapegin**
I use CSS Modules with Sass and I need this functionality to test components with CSS modules. 

```javascript
var hook = require('css-modules-require-hook');

hook({
  extension: ['.scss']
});
```

### CODE REVIEW

**Comment by sullenor** [comment]
Hi, thank you for your interest! And for the pr ofc :)

I think it will be better to make an array, so the user will be able to set up multiple extensions.

**Comment by sapegin** [comment]
Good idea, I’ll update the PR.

**Comment by sullenor** [comment]
Do you mind to change the options name to `extensions`?

**Comment by sapegin** [comment]
Sure. I used the word “extra” to emphasize that it will not disable hooking of the default `.css` extension.

**Comment by sullenor** [comment]
yeah, I got it :)

I decided to add another opportunity for preprocessing styles. So you'll be able to provide a custom function through the `preprocessCss` option. I suppose it will be useful for you.

I will publish the new version when you will finish your pr. If you will need any help - tell me :)

**Comment by sapegin** [comment]
Done.

**Comment by sullenor** [comment]
:+1:

**Comment by sullenor** [comment]
Published - v1.0.6

**Comment by sapegin** [comment]
Cool, thanks! :shipit:

**Pull request merged**
