### PR TITLE
upgrade to postcss 6

### LINKED ISSUE #93: update to postcss-6.0.1
I only checked that three test are failing when updating the dependencies to postcss-6.0.1:

```
  tokens
Node#before is deprecated. Use Node#raws.before
    1) compose-node-module
    2) multiple-dependencies
    3) multiple-sources

  1) tokens compose-node-module:
     postcss-modules-scope: /home/marcin/repos/postcss/css-modules-require-hook/test/tokens/cases/compose-node-module/source.css:3:3: referenced class name "i__imported_paragraph_0" in composes not found
  CssSyntaxError: /home/marcin/repos/postcss/css-modules-require-hook/test/tokens/cases/compose-node-module/source.css:3:3: referenced class name "i__imported_paragraph_0" in composes not found
  
    1 | .foo
    2 | {
  > 3 |   composes: paragraph from 'awesome-theme/common.css';
      |   ^
    4 | }
    5 | 

  2) tokens multiple-dependencies:
     postcss-modules-scope: /home/marcin/repos/postcss/css-modules-require-hook/test/tokens/cases/multiple-dependencies/source.css:3:3: referenced class name "i__imported_text_0" in composes not found
  CssSyntaxError: /home/marcin/repos/postcss/css-modules-require-hook/test/tokens/cases/multiple-dependencies/source.css:3:3: referenced class name "i__imported_text_0" in composes not found
  
    1 | .article
    2 | {
  > 3 |   composes: text from './colors.css';
      |   ^
    4 |   composes: medium from './fonts.css';
    5 |   composes: mediumBottom mediumTop from './margins.css';

  3) tokens multiple-sources:
     postcss-modules-scope: /home/marcin/repos/postcss/css-modules-require-hook/test/tokens/cases/multiple-sources/source.css:3:3: referenced class name "i__imported_oceanic_0" in composes not found
  CssSyntaxError: /home/marcin/repos/postcss/css-modules-require-hook/test/tokens/cases/multiple-sources/source.css:3:3: referenced class name "i__imported_oceanic_0" in composes not found
  
    1 | .article
    2 | {
  > 3 |   composes: oceanic from './colors.css';
      |   ^
    4 | }
    5 | 
```

### PR DESCRIPTION
**Pull request by longlho**
fix #93

### CODE REVIEW

**Comment by longlho** [comment]
ping @sullenor

**Comment by longlho** [comment]
can someone take a look at this PR?

**Comment by sullenor** [comment]
I'll check it today. Sorry, that it took too long.

**Comment by longlho** [comment]
tks a lot!

**Pull request merged**
